    include /www/server/panel/vhost/nginx/extension/supabase.guelichweb.store/auth-header.conf;

    location ^~ /login/ {
        try_files $uri $uri/ /login/index.html;
    }

    location = /login {
        return 302 /login/;
    }

    location ^~ /auth/ {
        location ~ \.php$ {
            try_files $uri =404;
            fastcgi_pass unix:/tmp/php-cgi-83.sock;
            fastcgi_index index.php;
            include fastcgi.conf;
            include pathinfo.conf;
        }
    }
